apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-starter-master
  name: go-starter-master
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: go-starter-master
  type: LoadBalancer
status:
  loadBalancer: {}