apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-starter-stage
  name: go-starter-stage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: go-starter-stage
  type: LoadBalancer # Can be ClusterIP for internal exposure
status:
  loadBalancer: {}